const FALLBACK_TRACKS: Track[] = [
  {
    id: '1',
    title: 'Level Up - Travis Scott x Future Type Beat | Dark Trap Instrumental (92 BPM - F#m)',
    bpm: 92,
    key: 'F# Minor',
    genre: 'Trap / Dark Hip-Hop',
    duration: '0:53',
    audioUrl: 'https://hnliahdtcbuvggxhmzej.supabase.co/storage/v1/object/public/audio-previews/Level%20Up.mp3',
    priceMp3: '$29.99',
    priceWav: '$49.99',
    priceStems: '$149.99',
  },
  {
    id: '2',
    title: 'Sip of Me - J. Cole x Joey Bada$$ Type Beat | Chill Lofi Boom Bap Instrumental (85 BPM - Dm)',
    bpm: 85,
    key: 'D Minor',
    genre: 'Boom Bap / Chill Lofi Hip-Hop',
    duration: '0:54',
    audioUrl: 'https://hnliahdtcbuvggxhmzej.supabase.co/storage/v1/object/public/audio-previews/Sip%20of%20Me.mp3',
    priceMp3: '$29.99',
    priceWav: '$49.99',
    priceStems: '$149.99',
  },
  {
    id: '3',
    title: 'Badin M 2 - Freddie Gibbs x MF DOOM Type Beat | Underground Boom Bap Instrumental (100 BPM - Am)',
    bpm: 100,
    key: 'A Minor',
    genre: 'Boom Bap / Underground Hip-Hop',
    duration: '0:49',
    audioUrl: 'https://hnliahdtcbuvggxhmzej.supabase.co/storage/v1/object/public/audio-previews/Badin%20M%202.mp3',
    priceMp3: '$29.99',
    priceWav: '$49.99',
    priceStems: '$149.99',
  },
];